INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (2, 'PORT AU PRINCE', 183400, -722100, '+050');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (3, 'ARQUIPELAGO SÃO PEDRO E SÃO PAULO', 5512, -292036, '+020');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (4, 'ILHA DAS PACAS', 1218, -493742, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (7, 'FURO GRANDE DO JURUPARI', 112, -502900, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (8, 'ILHA DO BRIGUE', 5518, -500424, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (9, 'GURUPA', -12430, -513912, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (10, 'JUPATI', -100, -503630, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (11, 'BARCARENA', -13000, -483900, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (12, 'CIA. DE PESCA PINA', -12206, -482900, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (13, 'CHAVES', -830, -495918, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (14, 'ALMEIRIM', -13200, -523436, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (15, 'VISEU', -11230, -460630, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (16, 'AFUA', -936, -502336, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (17, 'VAL DE CÃES', -12348, -482930, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (18, 'PORTO DE BELEM', -12612, -482936, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (19, 'VILA NAZARE', -930, -490900, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (20, 'ILHA DO CALDEIRÃO', -3500, -510100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (21, 'CANAL DO VIEIRA GRANDE', -1200, -504100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (22, 'SÃO JOSÉ DO TAJAPURU', -10736, -505530, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (23, 'ILHA DO MOSQUEIRO', -10954, -482830, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (24, 'CANIVETE', 3030, -502448, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (25, 'VIGIA', -5100, -481748, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (26, 'SOURE', -4400, -483100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (27, 'ABADE', -4224, -475300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (28, 'FABRICA ECOMAR', -5048, -480824, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (30, 'VILA SÃO JOSE DO PIRARUCU', -1448, -504942, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (32, 'COLARES', -5600, -481748, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (33, 'VILA CURUMU', -5618, -505230, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (34, 'SAO SEBASTIAO', -5900, -504830, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (35, 'ANGELIM', -11900, -502100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (36, 'VILA MALATO', -13006, -485436, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (37, 'PONTA GROSSA', -13200, -484500, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (38, 'PORTO DE VILA DO CONDE', -13224, -484512, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (39, 'ABAETETUBA - INPEX', -14236, -485254, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (40, 'COCALZINHO', -13854, -492118, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (41, 'ATRACADOURO DE BREVES', -14130, -502900, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (42, 'NOVA VIDA DO BISPO', -10754, -511342, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (43, 'SAO LUIS DO TAJAPURU', -14148, -503600, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (44, 'RIO TOCANTINS', -15218, -490918, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (45, 'PONTA NEGRA', -13736, -491324, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (46, 'ILHA DE SANTA HELENA', -14800, -501630, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (47, 'CURRALINHO', -14918, -494900, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (48, 'CAMETA', -21524, -493000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (49, 'ACAITUBA', 2600, -502512, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (50, 'SSN - 41', -342, -510936, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (52, 'CIA DOCAS DO PORTO DE SANTANA', -342, -511006, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (53, 'PORTO DE SANTANA - ICOMI', -324, -511054, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (54, 'MAZAGAO', -654, -511654, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (55, 'AJUDANTE', -1330, -512324, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (56, 'SERRARIA RIO MATAPI', -224, -511206, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (57, 'BOA VISTA DAS PRACUBINHA', -2818, -512136, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (58, 'PONTA DO CÉU', 4536, -500648, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (59, 'PONTA DO CÉU I (IGARAPÉ GDE. DO CURUÁ)', 4542, -500706, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (60, 'LIMÃO DO CURUÁ', 4524, -501036, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (61, 'IGARAPÉ GRANDE DON CURUÁ', 5454, -500730, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (62, 'ESCOLA DO IGARAPÉ GRANDE DO CURUÁ', 4548, -500700, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (63, 'PORTO DE MACAPÁ', 206, -510236, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (64, 'CARACURU', -5606, -522612, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (65, 'PAGA DÍVIDAS', -10736, -521236, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (66, 'MUNGUBA', -5536, -522554, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (67, 'JUPATITUBA', -10624, -522024, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (68, 'SAUDADE', -11036, -520136, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (69, 'SAUDADE I', -11036, -520142, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (71, 'ILHA BELA - PARTE NORTE', -234230, -452030, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (72, 'FUNDEADOURO DE SALINÓPOLIS', -3700, -472100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (73, 'ILHA DO MACHADINHO', -1048, -484600, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (74, 'CABO MAGUARI', -1500, -482500, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (75, 'PONTA TAIPU', -3942, -480300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (76, 'ILHA DOS GUARAS', -3436, -475430, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (77, 'ILHA DOS GUARÁS I', -3412, -475500, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (78, 'PORTUSIL', -4306, -504642, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (79, 'BOIUCUCANGA', -5306, -463718, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (80, 'CAETE', -5800, -462400, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (81, 'PONTA DOS ÍNDIOS', 40430, -513836, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (82, 'SANTO ANTÔNIO DO OIAPOQUE', 35318, -514736, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (83, 'CASSIPORE', 35100, -510800, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (84, 'TRAPICHE DO OIAPOQUE', 35048, -515006, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (85, 'PLATAFORMA PENROD', 30000, -492000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (86, 'ATENCAO VERIFICAR ESTA ESTACAO', 111106, -1111106, '+000');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (87, 'SANTA MARIA DO COCAL', 23530, -505100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (88, 'IGARAPÉ DO INFERNO', 20548, -503000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (89, 'PONTA GUARA', 11300, -495300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (91, 'ILHA BELA - PARTE SUL', -234748, -452230, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (93, 'ALCANTARA', -22436, -442518, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (94, 'RIO JERIJÓ', -22500, -442400, '-030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (95, 'PORTO DE ITAQUI', -23436, -442212, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (96, 'BOA RAZAO', -24700, -442200, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (97, 'AREIA BRANCA - CONTINENTE', -45730, -370818, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (98, 'ILHA DO CAJUAL - ITAUNA', -22524, -443000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (99, 'TERMINAL DA ALUMAR', -24042, -442148, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (100, 'RIO ANIL', -23136, -441742, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (102, 'SAO JOAO', -11854, -445342, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (103, 'MANGUNCA', -13948, -444030, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (104, 'SAO LUIS', -23136, -441842, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (105, 'QUEBRA-POTE', -24500, -441800, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (106, 'PERICAUA', -15800, -443006, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (107, 'ILHA DE SANTANA', -21642, -433742, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (108, 'BACANGA II', -23242, -441500, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (109, 'TURIACU II', -13830, -452118, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (110, 'TURIACU III', -12430, -452500, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (111, 'CUMA', -20712, -443306, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (112, 'BACANGA I', -23248, -441818, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (113, 'TURIACU IV', -13600, -451600, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (114, 'SAO JOSE DO RIBAMAR', -23300, -440400, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (116, 'PRIMEIRA CRUZ', -23018, -432612, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (117, 'PORTO DE TUTOIA', -24554, -421630, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (118, 'BARRA DO RIO PREGUICAS', -23300, -424400, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (119, 'TERMINAL DA PONTA DA MADEIRA', -23354, -442242, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (120, 'FUNDEIO (PONTO A)', -22048, -441236, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (121, 'FUNDEIO (PONTO B)', -15600, -435212, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (123, 'PERIZES', -25630, -442530, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (124, 'PORTO DE LUIS CORREIA', -25106, -413842, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (125, 'BARRA DO TIMONHA', -25648, -411936, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (126, 'ACARAU', -25000, -400730, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (127, 'CAMOCIM', -25324, -405042, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (128, 'PARACURU I', -32300, -390000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (129, 'MUNDAU', -31100, -392230, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (130, 'PECEM - AANDERAA', -33230, -384930, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (131, 'PONTA DO PECEM', -33248, -384842, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (132, 'TERM. PORT. DO PECÉM', -33206, -384754, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (133, 'PORTO DE MUCURIPE', -34254, -382836, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (134, 'BARRA DO RIO JAGUARIBE', -42600, -374600, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (135, 'PORTO DE AREIA BRANCA - TERMISA', -44930, -370224, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (136, 'PONTA CAICARA', -50306, -360306, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (137, 'ALAZAO', -50600, -363606, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (138, 'CABO CALCANHAR', -50842, -353054, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (139, 'ENSEADA DE PITITINGA', -52218, -352006, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (140, 'PORTO DE GUAMARÉ', -50618, -361906, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (141, 'PORTO DE MACAU', -50600, -364024, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (142, 'PONTA DO REDUTO', -53136, -353800, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (143, 'MAXARANGUAPE', -53136, -351530, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (144, 'ATOL DAS ROCAS', -35200, -334900, '+020');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (145, 'PORTO DE NATAL', -54618, -351218, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (146, 'TRAPICHE DA CPRN', -54642, -351230, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (147, 'BASE NAVAL DE NATAL', -54736, -351306, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (148, 'LAGOA GUARAIRAS', -61024, -350706, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (149, 'TIBAU DO SUL', -61112, -350606, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (150, 'CABO BACOPARI', -62336, -350000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (151, 'PORTO DE CABEDELO', -65812, -345024, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (152, 'PONTA DE PEDRAS', -73748, -344830, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (153, 'ILHA DE ITAMARACA', -74630, -345318, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (154, 'PORTO DO RECIFE', -80324, -345206, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (155, 'TAMANDARE', -84536, -350600, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (156, 'PORTO DE SUAPE', -82354, -345736, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (157, 'PORTO DE PEDRAS', -91030, -351730, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (158, 'PORTO DE MACEIO', -94100, -354330, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (159, 'JEQUIA', -100424, -355830, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (160, 'PONTAL DO CURURIPE', -100936, -360806, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (161, 'PIAÇABUÇU', -102424, -362612, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (162, 'PENEDO', -101724, -363500, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (163, 'FAROL DE PEBA - AL', -102924, -362312, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (164, 'SERRÃO', -102512, -363348, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (165, 'BARRA DO RIO SAO FRANCISCO', -103012, -362400, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (166, 'CABECO', -103012, -362400, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (167, 'TERMINAL MARÍTIMO INÁCIO BARBOSA', -105000, -365542, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (168, 'FAROL DE SERGIPE(ATALAIA)', -105800, -370200, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (169, 'BARRA DO RIO SERGIPE', -105406, -370254, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (170, 'POXIM', -105642, -370300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (171, 'TANQUES', -105330, -370254, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (172, 'PLATAFORMA PCM-I', -110000, -370000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (173, 'CAPITANIA DOS PORTOS DE SERGIPE', -105512, -370248, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (174, 'BARRA DO RIO REAL', -112442, -372606, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (175, 'FAROL SERGIPE', -105806, -370254, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (176, 'FERNANDO DE NORONHA - BAIA DE SE', -35218, -322530, '+020');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (177, 'FERNANDO DE NORONHA-BAIA DE S. ANTONIO', -35000, -322412, '+020');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (179, 'RIO ITARIRI', -120400, -374100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (180, 'GARCIA D`AVILA', -123354, -380012, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (181, 'CACHOEIRA', -123612, -385812, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (182, 'SÃO FRANCISCO DO CONDE', -123748, -384100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (183, 'NAJE', -124336, -385554, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (184, 'PORTO DE MADRE DE DEUS', -124442, -383718, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (185, 'TERMINAL ALVES CAMARA', -124454, -383718, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (186, 'TERMINAL USIBA', -124918, -381300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (187, 'MARAGOJIPE', -124654, -385424, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (188, 'SAO ROQUE', -125106, -385030, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (189, 'ILHA DE ITAPARICA', -125248, -384112, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (190, 'ARATU IATE CLUBE', -124848, -382736, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (191, 'BASE NAVAL DE ARATU', -124748, -382930, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (192, 'VALENCA', -132154, -390436, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (193, 'MORRO DE SAO PAULO', -132218, -385500, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (194, 'PORTO DE SALVADOR', -125754, -383100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (195, 'CAPITANIA DE SALVADOR', -125824, -383100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (196, 'BARRA DO CAMAMU', -135500, -390006, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (197, 'PORTO DE ILHÉUS', -144648, -390136, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (198, 'ILHÉUS - PORTO VELHO', -144800, -390218, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (199, 'CANAVIEIRAS', -154100, -385700, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (200, 'SANTA CRUZ DE CABRÁLIA', -161636, -390124, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (201, 'PORTO SEGURO', -162712, -390354, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (202, 'CUMURUXATIBA', -170600, -391042, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (203, 'PORTO DE CARAVELAS', -174412, -391548, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (204, 'NOVA VICOSA', -175324, -392218, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (205, 'ABROLHOS', -175748, -384154, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (206, 'MUCURI', -180612, -393400, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (207, 'CONCEIÇÃO DA BARRA', -183630, -394348, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (209, 'REGENCIA', -193836, -394924, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (210, 'CEPEMAR', -201918, -402006, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (211, 'PONTA DE MEAÍPE', -204442, -403212, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (212, 'PIRAQUE-ACU', -195718, -400900, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (213, 'TERMINAL DE BARRA DO RIACHO', -195018, -400324, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (215, 'PORTO DE VITORIA', -201912, -401906, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (216, 'EAMES', -201936, -401736, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (217, 'CAPITANIA DOS PORTOS DO ESPÍRITO SANTO', -201906, -401748, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (218, 'PORTO DE TUBARÃO', -201718, -401436, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (219, 'ILHA DA TRINDADE', -203030, -291836, '+020');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (220, 'ILHA DA TRINDADE - AANDERAA', -203030, -291836, '+020');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (221, 'GUARAPARI', -204000, -402930, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (222, 'TERMINAL DA PTA DO UBU', -204712, -403412, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (223, 'BARRA DO ITAPEMIRIM', -210012, -404824, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (225, 'SAO JOAO DA BARRA', -213812, -410400, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (226, 'ATAFONA', -213900, -410400, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (227, 'RIO DAS OSTRAS', -223148, -415630, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (228, 'BUZIOS', -224448, -415300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (229, 'IATE CLUBE COSTA AZUL', -225236, -420124, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (230, 'SÃO TOMÉ', -220242, -410312, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (231, 'BARRA DO FURADO', -220536, -410818, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (232, 'TERMINAL DE IMBETIBA', -222306, -414612, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (233, 'ILHA DE SANTANA', -222424, -414224, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (234, 'DEPÓSITO DE COMBUSTÍVEIS DA MARINHA', -225000, -431054, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (235, 'ILHA DA CONCEICAO', -225206, -430712, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (236, 'BATALHA', -224348, -430748, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (237, 'BNRJ - CAIS DA MARÍTIMA', -225212, -430806, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (238, 'ILHA DE BROCOIO', -224518, -430700, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (239, 'BNRJ - DIQUE CAIS NE', -225206, -430800, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (240, 'ILHA DE PAQUETA', -224536, -430636, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (241, 'RIO MERITI-(BATALHÃO DE FUZ. NAVAIS)', -224836, -431718, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (242, 'ILHA DO BOQUEIRÃO', -224630, -430924, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (243, 'ILHA DO BOQUEIRÃO I', -224642, -430930, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (244, 'SACO DO PINHAO', -224648, -431018, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (245, 'PIRACAO', -230100, -433500, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (246, 'FOZ DO RIO MERITI', -224848, -431724, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (247, 'ILHA DO ENGENHO', -225024, -430624, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (248, 'BOM JESUS', -225200, -432100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (249, 'ESTACAO DAS BARCAS - PAQUETA', -224542, -430624, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (250, 'MOCANGUE GRANDE', -225218, -430754, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (251, 'ESCOLA NAVAL', -225448, -430936, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (252, 'PONTA DO CAJU', -225224, -431212, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (253, 'ARSENAL DE MARINHA DO RIO DE JANEIRO', -225348, -431012, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (254, 'PORTO DO RIO DE JANEIRO', -225342, -431000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (255, 'IATE CLUBE DO RIO DE JANEIRO', -225712, -431030, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (256, 'ILHA FISCAL', -225348, -431000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (257, 'PONTA DA ARMACAO', -225300, -430806, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (258, 'ILHA DA MADEIRA', -225518, -435100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (259, 'PONTA GUAIA-ILHA DA MADEIRA', -225542, -435036, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (261, 'PORTO DE ITAGUAÍ', -225554, -435030, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (262, 'FORTALEZA DE SANTA CRUZ', -225612, -430800, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (264, 'ITACURUCA', -225654, -435306, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (265, 'PONTA DO MORRO DO AFONSO - SEPETIBA', -225606, -435754, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (266, 'IMBUI', -225700, -430700, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (267, 'PONTA NEGRA', -225812, -424136, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (268, 'PORTO DO FORNO', -225818, -420048, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (269, 'PRAIA DE ITAIPU', -225824, -430248, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (270, 'COPACABANA - SALVAMAR', -225906, -431118, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (271, 'CLUB MED MANGARATIBA', -225948, -440542, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (272, 'SEPETIBA', -225912, -434130, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (273, 'TERMINAL DA ILHA GUAÍBA', -230000, -440154, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (274, 'ITAORNA', -230018, -442806, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (275, 'FAROL CASTELHANOS', -231006, -440536, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (276, 'ESTALEIRO VEROLME', -230018, -441454, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (277, 'PORTO DE ANGRA DOS REIS', -230048, -441854, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (278, 'ENSEADA DE BRACUI', -225724, -442354, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (279, 'RECREIO DOS BANDEIRANTES', -230218, -432812, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (280, 'PIRAQUARA', -230036, -442636, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (281, 'BARRA DA TIJUCA', -230100, -431748, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (282, 'ENSEADA DE PALMAS', -230924, -440818, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (283, 'COLEGIO NAVAL', -230106, -441936, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (284, 'MARAMBAIA', -230348, -435930, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (285, 'SITIO FORTE', -230800, -441700, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (286, 'PARATI', -231318, -444230, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (287, 'ENSEADA DO SOBRADO', -232030, -443930, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (288, 'UBATUBA', -232706, -450248, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (289, 'PORTO DE SAO SEBASTIAO', -234836, -452354, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (290, 'MONTAO DE TRIGO', -235130, -454648, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (291, 'PIACAGUERA', -235218, -462230, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (292, 'SACO DO SOMBRIO', -235406, -451500, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (293, 'CONCEICÃOZINHA', -235800, -461800, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (294, 'COSIPA', -235324, -462712, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (295, 'MORTONA', -235742, -461824, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (296, 'IGUAPE', -244148, -473406, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (297, 'PORTO DE SANTOS - TORRE GRANDE', -235706, -461818, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (298, 'ILHA DE BARNABE', -235536, -462000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (299, 'PRATICAGEM SANTOS', -235930, -461806, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (300, 'CAPITANIA DOS PORTOS DE SÃO PAULO', -235724, -461830, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (301, 'COSIPA I', -235224, -462236, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (302, 'ILHA DAS PALMAS', -240030, -461930, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (303, 'ILHA DA MOELA', -240306, -461606, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (304, 'GUARAU', -242248, -465912, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (305, 'PONTA PARANAPUA', -242400, -470042, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (306, 'PRAIA DO ARAÇÁ', -244154, -472718, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (307, 'BARRA DE ICAPARA', -244124, -472754, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (308, 'BARRA DE PERUIBE', -242012, -470030, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (309, 'PONTA DA PRAINHA', -242100, -465948, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (310, 'CANANEIA', -250100, -475530, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (311, 'BOM ABRIGO', -250718, -475142, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (312, 'GUARATUBA IATE CLUBE', -255224, -483448, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (313, 'CAIOBÁ', -255124, -483406, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (314, 'ANTONINA', -252636, -484136, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (315, 'ILHA DAS COBRAS', -252854, -482600, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (316, 'BARRA DE PARANAGUÁ - CANAL SE', -253224, -481742, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (317, 'CAPITANIA DOS PORTOS DO PARANA', -253048, -482848, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (318, 'PORTO DE PARANAGUÁ - CAIS OESTE', -253006, -483130, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (319, 'CAIS TENENGE', -253254, -482300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (320, 'CAIS DA TECHINT', -253306, -482148, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (321, 'BARRA DE PARANAGUÁ - CANAL DA GALHETA', -253400, -481900, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (322, 'PONTA DO POCO', -253300, -482200, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (323, 'PORTO DO RIO PEQUERE - LFM-CEM-APPA', -253430, -482106, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (324, 'TERMINAL PORTUÁRIO DA PONTA DO FÉLIX', -252718, -484042, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (325, 'PORTO DE PARANAGUÁ - CAIS LESTE', -253006, -483012, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (326, 'PONTA DA GALHETA', -253418, -481906, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (327, 'ILHA DA PAZ', -261042, -482906, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (328, 'DEL. DA CAP.EM SÃO FRANCISCO DO SUL', -261442, -483824, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (329, 'ILHA DA RITA', -261506, -484230, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (330, 'JOINVILLE IATE CLUBE', -261730, -484624, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (331, 'PORTO DE SÃO FRANCISCO DO SUL', -261412, -483806, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (332, 'PENHA', -264612, -483906, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (333, 'CLUBE NAÚTICO CRUZEIRO DO SUL', -261442, -483830, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (334, 'IATE CLUBE BOA VISTA', -261830, -484924, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (335, 'ESTALEIRO DETROIT', -265142, -484330, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (336, 'PORTO DE ITAJAI', -265406, -483942, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (337, 'DEL. DA CAP. DOS PORTOS EM ITAJAI', -265418, -483936, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (338, 'PRATICAGEM DO PORTO DE ITAJAÍ', -265406, -493936, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (339, 'PORTO BELO', -270924, -483300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (340, 'ILHA DO ARVOREDO', -271748, -482130, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (341, 'PORTO DE FLORIANOPOLIS', -273518, -483324, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (342, 'CAPITANIA DOS PORTOS DE SANTA CATARINA', -273542, -483400, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (343, 'PORTO DE IMBITUBA', -281348, -483900, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (344, 'PORTO DE LAGUNA', -283100, -484700, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (345, 'FAROL DE SANTA MARTA', -283600, -484842, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (346, 'ARARANGUA', -285512, -492012, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (347, 'TORRES', -292048, -494330, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (348, 'TRAMANDAI', -295800, -500700, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (349, 'PRAÇA DA HARMONIA', -300154, -511424, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (350, 'SOLIDAO', -304248, -502812, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (351, 'LARANJAL', -314600, -521330, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (352, 'PELOTAS', -314600, -522000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (353, 'ASD-DEPREC', -320206, -520406, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (354, 'SAO JOSE DO NORTE', -320054, -520236, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (355, 'SARITA', -323748, -522542, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (356, 'TERMINAL DE PETROLEIROS', -320406, -520506, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (357, 'PORTO DO RIO GRANDE', -320724, -520612, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (358, 'CAIS DA PRATICAGEM DO RIO GRANDE', -320818, -520612, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (359, 'BASE COMANDANTE FERRAZ', -620506, -582342, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (360, 'BAIA DO ALMIRANTADO - BANCO DA OHI', -620500, -582400, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (361, 'ILHA ELEFANTE-CABO FOSSATTI', -611648, -551248, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (362, 'BAIA DE FILDES', -621100, -585130, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (363, 'PONTA ANELISE', -621106, -585136, '-000');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (364, 'ARTIGAS', -621100, -585200, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (365, 'ARDLEY COVE', -621200, -585800, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (366, 'DECEPCION ISLAND', -625800, -604200, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (367, 'HOPE BAY - ESPERANZA', -632400, -565900, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (368, 'GERLACHE STRAIT', -643300, -620100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (369, 'PROSPECT POINT - BISCOE', -660000, -652100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (370, 'PORTO DE SAN JUAN', 182800, -660700, '+040');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (371, 'PORTO DE LA GUAIRA', 103700, -665600, '+040');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (372, 'PORTO DE CARTAGENA', 102136, -753254, '+050');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (373, 'PORTO DE PARAMARIBO', 54936, -550842, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (374, 'MONDING NICKERIE', 55800, -570000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (375, 'PORTO DE CAYENA', 45500, -522000, '+040');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (376, 'MONT D`ARGENT', 42300, -514136, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (377, 'PORTO DE MONTEVIDEU', -345500, -561300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (378, 'LA PALOMA', -344000, -545500, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (379, 'PORTO DE BUENOS AIRES', -343600, -582200, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (380, 'PORTO DE MAR DEL PLATA', -380300, -573300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (381, 'WALVIS BAY - NAMIBIA', -225700, 142954, '-010');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (384, 'PORTO DE LUANDA', -84700, 131400, '-010');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (385, 'PORTO DE NAMIBE', -151200, 120900, '-010');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (386, 'PONTA PLAZA', -111106, -111106, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (387, 'BARRA GRANDE', -135324, -385712, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (388, 'VILA CURUMU I', -5954, -505000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (389, 'NOVA VIDA DO BISPO I', -10718, -511336, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (390, ' SAO LUÍS DO TAJAPURU I', -14142, -503524, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (391, 'BOA ESPERANÇA', -10812, -505442, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (392, 'TRAPICHE DE SANTA HELENA ', -14718, -501630, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (394, 'NOVA ATALAIA', -105624, -370206, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (395, 'TAUÁ', -24754, -442424, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (396, 'CAMARÃO TUBA', -1324, -493124, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (397, 'ILHA DOS GUARÁS II', -3436, -475430, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (398, 'FURO GRANDE DO JURUPARÍ I', -154, -503506, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (399, 'ILHA DE ANHATOMIRIM', -272542, -483348, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (400, 'MAIAUATÁ', -15112, -490106, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (401, 'VILA DO CARMO', -22700, -492630, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (402, 'MOCAJUBA', -23500, -493042, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (403, 'MOLHE SUL DE LAGUNA', -282936, -484512, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (404, 'DELEGACIA DE LAGUNA', -282906, -484700, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (405, 'ITAJAÍ CPSUL/IBAMA', -265700, -484542, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (406, 'PORTO DE AÇU', -214854, -405954, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (407, 'CPSUL-IBAMA', -265700, -484524, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (408, 'ITAJAÍ-EPAGRI', -265448, -483912, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (409, 'NOVA DEL DA CAP DOS PORTOS EM ITAJAÍ ', -265436, -483912, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (410, 'SANTANA - PACMARE', -324, -511054, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (411, 'ESTALEIRO DETROIT I', 0, 0, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (412, 'CIA DOCAS SANTANA - PACMARE', -342, -511006, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (413, 'PAGA DÍVIDAS I', -11236, -520736, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (414, 'MUNGUBA I', -5230, -522548, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (415, 'JARILANDIA I', -10730, -515942, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (417, 'FAROL ATALAIA', -105806, -370206, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (418, 'NOVA ATALAIA', -105624, -370206, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (419, 'ILHA DO BERNARDO', -230124, -435712, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (420, 'CADIM', -230324, -435918, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (421, 'TESTE XINGU', 0, 0, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (422, 'TESTE JOCA NORTE', 0, 0, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (423, 'TESTE JOCA SUL', 0, 0, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (424, 'ILHA DOS GUARÁS III', -3554, -475454, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (425, 'TGN TRANSPETRO (TERMINAL DE GÁS NATURAL)', -224818, -430718, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (426, 'BARRA DO ITABAPUANA', -211806, -405748, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (427, 'EISA - ESTALEIRO ILHA', -224712, -431124, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (428, 'PAU CAVADO', 1130, -504754, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (429, 'TESTE CPRN', -272624, -482830, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (430, 'MERCADO MUNICIPAL DE PEIXE - MACAÉ', -222230, -414630, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (431, 'IATE CLUBE DE ITACURUÇA', -225542, -435418, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (432, 'CS NORSUL TROMBETAS', -23854, -442212, '-030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (433, 'IATE CLUBE CABEÇUDAS', -265542, -483742, '-030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (434, 'TEPORTI', -265236, -484242, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (435, 'UNIVERSIDADE FEDERAL DO PARÁ (UFPA)', -12612, -482936, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (436, 'IATE CLUBE DE RAMOS', -225024, -431454, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (437, 'UNIVERSIDADE FEDERAL DO PARA - UFPA', -12842, -482718, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (438, 'ACARÁ ', -13900, -482600, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (439, 'CUJUPE', -23018, -443112, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (440, 'CLUBE CAPRI', -261042, -482906, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (441, 'ILHA DO RIJO', -224712, -430900, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (442, 'AUTAZES', -33312, -590748, '+040');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (443, 'APA GUAPIMIRIM', -224036, -425036, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (444, 'FRANÇA TESTE', -253000, -482942, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (445, 'EBN', -225554, -435054, '-030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (446, 'TESTE FLU', -225606, -430800, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (447, 'TESTE FLU', -225606, -430800, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (448, 'TESTE FLU', -225606, -430800, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (449, 'TESTE', -202000, -202000, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (450, 'PORTO DO AÇU - T2 - DARSENA 04', -215230, -410036, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (451, 'PORTO DO AÇU - T2 - DARSENA 02', -215112, -410024, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (452, 'FURO DO CAPIM', -13506, -485300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (453, 'FOZ DO ACARÁ', -13900, -482600, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (454, 'ESTALEIRO JURONG', -195206, -400424, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (455, 'TERMINAL PORTUÁRIO DA GE', -225154, -430654, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (456, 'TERMINAL DA CSA', -225712, -434724, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (457, 'CAESA', 118, -510300, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (458, 'SSN-5', -310154, -520430, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (459, 'TERMINAL SALINOR', -50618, -363954, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (460, 'TERMINAL TROCADEIROS', -265318, -484100, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (461, 'ILHA DE JAGUANUM', -225948, -435554, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (462, 'COPACABANA TESTE', -225906, -431118, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (463, 'PONTA DO CAJU - ESTALEIRO BRASCO', -225200, -431236, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (464, 'OGIVA IATE CLUBE', -225224, -420024, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (465, 'ESTALEIRO INHAÚMA - PONTA DO CAJU', -225218, -431218, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (466, 'GRADIM', -224936, -430542, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (467, 'PONTA NEGRA I ', -225736, -424130, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (468, 'PORTO DO AÇU - TERMINAL T-OIL', -214848, -405954, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (469, 'PORTO DO RIO', -225336, -431254, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (470, 'TESTE CP+', -204618, -403136, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (471, 'BOIA PONTA DO UBU', -204618, -403130, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (472, 'SAMARCO', -204618, -403136, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (473, 'JURERÊ', -272600, -482848, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (474, 'POLÍCIA FEDERAL  - CODESA', -201918, -402030, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (475, 'TERMINAL DE BARCAÇAS OCEÂNICAS', -201530, -401312, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (476, 'PORTO DE PARANAGUA - CAIS LESTE I', -253000, -482942, '-030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (477, 'TECON - RJ', -235218, -431500, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (478, 'TESTE ABADE', -3600, -475454, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (479, 'ABADE I', -4218, -475254, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (480, 'TERMINAL DA TERNIUM', -225712, -434724, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (481, 'PORTO DE SUAPE - SISMO', -82336, -345736, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (482, 'ESTALEIRO BRASFELS', -230000, -441442, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (483, 'BASE NAVAL DO RIO DE JANEIRO', -225500, -430800, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (484, 'TIPLAM', -235224, -462224, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (485, 'CAMETA I', -21442, -492942, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (486, 'PONTA NEGRA I', -13736, -491324, '+030');
INSERT INTO "estacao_maregrafica" ("cod_estacao_maregrafica", "nome_estacao_maregrafica", "latitude", "longitude", "fuso") VALUES (487, 'CAIS DA CODESA', -201918, -402012, '+030');
